// <auto-generated />
namespace L_OccitaneHugsData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_create_imageUrl_collumn_in_hug_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_create_imageUrl_collumn_in_hug_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201610181823227_Add_create_imageUrl_collumn_in_hug_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
